In [1]:
import numpy as np

## Datatypes

In [2]:
Array1 = np.arange(10)
Array2 = np.ones(10)*3
Array3 = np.array(["Anil","Mike","Ram"])
print("Array1 = ",Array1)
print("Array2 = ",Array2)
print("Array3 = ",Array3)

Array1 =  [0 1 2 3 4 5 6 7 8 9]
Array2 =  [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
Array3 =  ['Anil' 'Mike' 'Ram']


##### We have created 2 arrays Array1 and Array2. What are the differences you notice ?
##### Is there any difference between them. They both have 10 Elements. But you might have noticed in Array1 there is no dot(.) after the digit but in Array2 you have Numbers followed by a dot(.). Why?
##### Well, This is because of the Data type of the element present in an array. We can say/conclude that in Array1 we have all the elements are integers but were as in Array2 All the elements of float datatype... Let's Verify

In [3]:
print("Datatype of Array1 = ",Array1.dtype)
print("Datatype of Array2 = ",Array2.dtype)
print("Datatype of Array3 = ",Array3.dtype)

Datatype of Array1 =  int32
Datatype of Array2 =  float64
Datatype of Array3 =  <U4


#### Therefore, The datatype of an array is determined by the type of elements that it holds...

## Indexing and Slicing

#### Similar to python lists here Arrays can also accessed by indexing and slicing operations can also be performed

In [4]:
print(Array1[1],Array1[4],Array1[-1],Array3[1:2])  # This is the basic operation hope there is no need of explination...

1 4 9 ['Mike']


## SOME BASIC OPERATIONS

In [5]:
print("Array1 + 4 :",Array1+4)   # 4 will be added to every element of array....
print("Array1 / 2 :",Array1/2)   # Every element of Array1 is divided by 2....
print("Array1 ** 2 :",Array1**2)  # Every element is squared...

Array1 + 4 : [ 4  5  6  7  8  9 10 11 12 13]
Array1 / 2 : [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Array1 ** 2 : [ 0  1  4  9 16 25 36 49 64 81]


## Array Multiplication....
### In this case each element in one array is multiplied with the corresponding element of another array...

In [6]:
Array1 * Array2

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

## Matrix Multiplication....
### It is similar to the Multiplication operation of two matrices....
#### Normal Array1 * Array2 would result in error if no. of rows and no. of colomns not matched.....

In [7]:
Array3 = np.ones((3,3))
Array4 = np.ones((3,3))
print("Matrix Multiplication :")
print(Array3.dot(Array4))
print("Array Multiplication :")
print(Array3 * Array4)

Matrix Multiplication :
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
Array Multiplication :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Comparing Two Matrices/Arrays...

In [8]:
print("If shape is same then preforms element wise comparision... :",Array1 == Array2)
print("If shape is not same then Rises a warning and Finally Return false :",Array2 == Array3)

If shape is same then preforms element wise comparision... : [False False False  True False False False False False False]
If shape is not same then Rises a warning and Finally Return false : False


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


### min, max, sum, argmin, argmax, Statistical computations, flattening, reshaping and Sorting Operations....

In [9]:
TempArray = np.random.random(7)*100
print(TempArray)

[13.06962516 35.23155184 67.77641609 49.31664855 17.93325033 67.75611982
 43.59391649]


In [10]:
print("Maximum Element",TempArray.max())
print("Minimum Element",TempArray.min())
print("Sum of Elements",TempArray.sum())
print("The index, Where the Maximum element present :",TempArray.argmax())
print("The index, Where the Minimum element present :",TempArray.argmin())
print("Mean of Array Elements :",TempArray.mean())
print("Standard deviation of Array Elements :",TempArray.std())

Maximum Element 67.77641609097024
Minimum Element 13.06962515864214
Sum of Elements 294.6775282786558
The index, Where the Maximum element present : 2
The index, Where the Minimum element present : 0
Mean of Array Elements : 42.096789754093685
Standard deviation of Array Elements : 20.162895877440935


In [11]:
TempArray2 = np.random.random((5,3))
print(TempArray2)

[[0.789761   0.81465674 0.13914572]
 [0.01130502 0.45904402 0.39262605]
 [0.11001594 0.25510911 0.24294565]
 [0.80733889 0.01040291 0.55290232]
 [0.46651245 0.87861638 0.03788256]]


### Rows and columns sum

In [12]:
print("Sum of elements in Column Wise = ",TempArray2.sum(axis=0))  # Returns Sum of elements in columns (In This Case)-> E11 + E21 + E31 + E41 + E51 and so on for  2nd column and 3rd column.......[EXX = Element[Row][Column]]
print("Sum of elements in Row Wise = ",TempArray2.sum(axis=1))

Sum of elements in Column Wise =  [2.18493329 2.41782916 1.3655023 ]
Sum of elements in Row Wise =  [1.74356346 0.86297509 0.60807069 1.37064412 1.38301138]


### The above matix is of size 5x3. Flattening simply mean to unroll the matrix in to a vector..... The example will make you clear....

In [13]:
TempArray2.ravel() # By this the given TempArray2 Matrix is turned into a vector....

array([0.789761  , 0.81465674, 0.13914572, 0.01130502, 0.45904402,
       0.39262605, 0.11001594, 0.25510911, 0.24294565, 0.80733889,
       0.01040291, 0.55290232, 0.46651245, 0.87861638, 0.03788256])

### Reshaping simply mean changing the order of no. of rows and no. of columns.... The result will also be a matrix with the given/passed shape.....

In [14]:
print("Given (5,3)Matrix turned into (3,5) :")
print(TempArray2.reshape(3,5))
print("\n\nGiven (5,3)Matrix turned into (1,15) :")
print(TempArray2.reshape(1,15))
print("\n\nGiven (5,3)Matrix turned into (15,1) :")
print(TempArray2.reshape(15,1))

Given (5,3)Matrix turned into (3,5) :
[[0.789761   0.81465674 0.13914572 0.01130502 0.45904402]
 [0.39262605 0.11001594 0.25510911 0.24294565 0.80733889]
 [0.01040291 0.55290232 0.46651245 0.87861638 0.03788256]]


Given (5,3)Matrix turned into (1,15) :
[[0.789761   0.81465674 0.13914572 0.01130502 0.45904402 0.39262605
  0.11001594 0.25510911 0.24294565 0.80733889 0.01040291 0.55290232
  0.46651245 0.87861638 0.03788256]]


Given (5,3)Matrix turned into (15,1) :
[[0.789761  ]
 [0.81465674]
 [0.13914572]
 [0.01130502]
 [0.45904402]
 [0.39262605]
 [0.11001594]
 [0.25510911]
 [0.24294565]
 [0.80733889]
 [0.01040291]
 [0.55290232]
 [0.46651245]
 [0.87861638]
 [0.03788256]]


## Why Numpy? Why is it so famous? 
#### Numpy is very memory efficient. It is much faster than the default python list and tupples...
### To demonstrate the Efficiency of the Numpy lets perform an experiment.

In [15]:
A = range(100000)    # range is builtin function in python. It starts form 0 to passed (value-1).
%timeit [i**2 for i in A] # It simply performs square of the every element present in A. You can Find the Datatype of A using type() - function pass the A as parameter...
# The output here will be the time taken to perform the operation....

30.2 ms ± 434 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
A = np.arange(100000)
%timeit A**2
# The output here will be the time taken to perform the operation....

69.4 µs ± 532 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
import sys  # Simple python module/library provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter. It is always available.
l = range(10000)
print("Memory consumption of Python List for 10000 elements :",sys.getsizeof(1)*len(l)) # Size of one element * no. of elements

Array = np.arange(10000)
print("Memory consumption of Numpy Array for 10000 elements :",Array.size * Array.itemsize) # size and itemsize are two attributes for numpy arrays that gives of size of array times size of items in array....

Memory consumption of Python List for 10000 elements : 280000
Memory consumption of Numpy Array for 10000 elements : 40000


##### Comparing the above two outputs. Normal operation using default python function, time is in the order of milli seconds and micro seconds... But, by performing the same operation using numpy, time taken is in the order of micro seconds and in nano seconds.....
#### The memory Consumption of NUMPY array is much lesser than that of normal python list.....

#### IT IS CLEAR THAT THE NUMPY IS REALLY FAST AND MEMORY EFFICIENT

<img src="data/whyNumpyFast.png" width=800/>

### Please Use the link and see the image as in GitHub the image placed above is not showing: https://i.pinimg.com/736x/4f/4e/c8/4f4ec839e33d9fc419a35624f0d59dec.jpg
### The above image shows why the Numpy is fast....
##### Numpy array directly stores the values of the array elements(Size of simply 4 bytes).... But the python list(Right Side in the Image) stores the address where the value is present(Size of 14 bytes).... 


## Quick Review of basic operations

In [18]:
X = np.arange(10)
#1. Basic Operations
print("Given Matrix + 1 :",X + 1) # Every element added with 1
print("Given Matrix - 4 :",X - 4) # Every element Subtracted with 4
print("Given Matrix * 3 :",X * 3) # Every element Multiplied with 3
print("Given Matrix **3 :",X ** 3) # Every element powerd with 3
print("----------------------------------------------------------------")
#2. Array Multiplication
A1 = np.arange(6)
A2 = np.linspace(10,20,6)
print("A1 Matrix * A2 Matrix :",A1*A2) # Element wise Multiplication of one Matrix to another
print("----------------------------------------------------------------")
#3. Matrix Multiplication
print("Shape and Dimentions of Matrices A1 and A2 :",A1.shape,A2.shape,A1.ndim,A2.ndim)
print("Since both the arrays are of single dimentions... Their Matrix multiplication would be a Scaler :",A1.dot(A2)) # Matrix Multiplication is Done... 
print("----------------------------------------------------------------")
A1_2Dim = A1.reshape(3,2)
A2_3Dim = A2.reshape(2,3)
print("Matix multiplication of Given Matrices A1_2Dim and A2_3Dim")
print(A1_2Dim.dot(A2_3Dim))

Given Matrix + 1 : [ 1  2  3  4  5  6  7  8  9 10]
Given Matrix - 4 : [-4 -3 -2 -1  0  1  2  3  4  5]
Given Matrix * 3 : [ 0  3  6  9 12 15 18 21 24 27]
Given Matrix **3 : [  0   1   8  27  64 125 216 343 512 729]
----------------------------------------------------------------
A1 Matrix * A2 Matrix : [  0.  12.  28.  48.  72. 100.]
----------------------------------------------------------------
Shape and Dimentions of Matrices A1 and A2 : (6,) (6,) 1 1
Since both the arrays are of single dimentions... Their Matrix multiplication would be a Scaler : 260.0
----------------------------------------------------------------
Matix multiplication of Given Matrices A1_2Dim and A2_3Dim
[[ 16.  18.  20.]
 [ 68.  78.  88.]
 [120. 138. 156.]]


## Hope this session was helpful.... Thank you.
##### Notebook Prepared By : V.PoornaChand
https://www.linkedin.com/in/poorna-chand-902642177/