# What is NUMPY?
#### Numpy is simply a library that gives the functionality of crating arrays in the Python.

        1. Numpy is a library for scientific computing.
        2. Numpys stands for Numerical Python.
        3. Numpy consists of Multidimensional array objects and it has collection of 
           functions/routines to process those arrays.
        4. There are advantages of using Numpy
           a. Takes less memory as compared to List
           b. Processing speed of numpy array is much higher.

In [1]:
import numpy as np
# Here we import the numpy library and generally people use np as the common allias for using numpy.
# For this tutorial we follow np as the allias for numpy. (np - > called as allias here)

###  As part of working with Numpy, one of the first things you will do is create Numpy arrays. The main objective of this guide is to inform you about the different tools available to create Numpy arrays.

### There are three different ways to create Numpy arrays:

        1. Using Numpy functions
        2. Conversion from other Python structures like lists
        3. Using special library functions
        
#### Numpy is very similar to python lists.... Elements can also be accessed by slicing or indexing also as list do..... Then Why Numpy ? 
        1. Fast
        2. Memory Efficient
        3. Convinient to use...

# 1.Creating an Arrays....

1. By default python doesn't have the Arrays Concept. Numpy is something like an addon for Python that gives the functionality of Arrays... Let's look at some Basic operation on Array after creating Array using Numpy.
2. Creating array using array() function - This is something like manually creating the array as we pass the elements of the array maually....
3. Creating an array using arange() function - Here the arange(10) function return an array from 0 to 9. This is not refered to be as manually creating array. We are not passing array elements directly....
4. Creating an array using linspace() function - Here linspace(1,100,10) function returns an array starting from 1 to 100 equally divided into 10 parts....
---------------------------------------------------------------------------------------------------------------------------

5. If we need a matrix all with zeros or all with ones Numpy has functions to do that as well.

        These are the most commonly used numpy functions to create an Array...

In [2]:
Array1 = np.array([2,4,5,6,3,5,9]) # Creating array using array() function - This is something like manually creating the array as we pass the elements of the array maually....
Array2 = np.arange(10) # Creating an array using arange() function - Here the arange(10) function return an array from 0 to 9. This is not refered to be as manually creating array. We are not passing array elements directly....
Array3 = np.linspace(1,100,10) # Creating an array using linspace() function - Here linspace(1,100,10) function returns an array starting from 1 to 100 equally divided into 10 parts....
print("Array1 = ",Array1)
print("Array2 = ",Array2)
print("Array3 = ",Array3)

Array1 =  [2 4 5 6 3 5 9]
Array2 =  [0 1 2 3 4 5 6 7 8 9]
Array3 =  [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [3]:
Array4 = np.zeros(10) # This Function returns a single dimnetional array (1D Array) all the elements are of zeros
# Now How to create a  matrix of 2x2 or 3x3 or 5x5 with all the elements of zeros?
# Answer for this Question is simple We just need to pass the desired shape as parameters for zeros() function.
Array5_0 = np.zeros((2,2)) # This Function returns a 2x2 Matrix
Array5_1 = np.zeros((3,3)) # This Function returns a 3x3 Matrix
Array5_2 = np.zeros((5,5)) # This Function returns a 5x5 Matrix
print("Array4 = ",Array4)
print("Array5_0 = ")
print(Array5_0)
print("Array5_1 = ")
print(Array5_1)
print("Array5_2 = ")
print(Array5_2)

Array4 =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array5_0 = 
[[0. 0.]
 [0. 0.]]
Array5_1 = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array5_2 = 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
Array6 = np.ones(10) # This Function returns a single dimnetional array (1D Array) all the elements are of ones
# Now How to create a  matrix of 2x2 or 3x3 or 5x5 with all the elements of ones?
# Answer for this Question is simple We just need to pass the desired shape as parameters for ones() function.
Array7_0 = np.ones((2,2)) # This Function returns a 2x2 Matrix
Array7_1 = np.ones((3,3)) # This Function returns a 3x3 Matrix
Array7_2 = np.ones((5,5)) # This Function returns a 5x5 Matrix
print("Array4 = ",Array6)
print("Array7_0 = ")
print(Array7_0)
print("Array7_1 = ")
print(Array7_1)
print("Array7_2 = ")
print(Array7_2)

Array4 =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array7_0 = 
[[1. 1.]
 [1. 1.]]
Array7_1 = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array7_2 = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### The above discussed are the very common functions that are generally used by the people to create Matrices/Arrays. Here are some of the other methods/functions that are avaliable in NUMPY.


In [5]:
Array8 = np.empty([2,5])# The empty function creates an array. Its initial content is random and depends on the state of the memory.
Array9 = np.full((2,2), 3) # The full function creates a n * n array filled with the given value.
Array10 = np.eye(3,3) # The eye function lets you create a n * n matrix with the diagonal 1s and the others 0.
#np.identity(5) - returns Identity matrix. This function is similar to np.eye()
print("Array8 = ")
print(Array8)
print("Array9 = ")
print(Array9)
print("Array10 = ")
print(Array10)

Array8 = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array9 = 
[[3 3]
 [3 3]]
Array10 = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## We can Use some special Function to create the array/matrix as well...!!!(Using Random)

-> You can also use special library functions to create arrays. For example, to create an array filled with random values between 0 and 1, use random function. This is particularly useful for problems where you need a random state to get started.

In [6]:
Array11 = np.random.random((5,3))
print("Array11 = ")
print(Array11)

Array11 = 
[[0.44519173 0.7288023  0.39500588]
 [0.5029865  0.02225874 0.72835862]
 [0.37340969 0.89105087 0.74125453]
 [0.32248864 0.97793835 0.00842462]
 [0.49402031 0.37688932 0.31041011]]


### Arrays Have properties like shape and size :
#### 1. Array1.shape gives the shape of Array1. 
   
####     Array1.ndim gives the number fo dimention of the given array.
   
       For better understanding of this shape and Dimention Concept An Example of Image is Given Below....

In [7]:
print("Shape of Array1 :",Array1.shape) 
print("Shape of Array2 :",Array2.shape)
print("Shape of Array3 :",Array3.shape) 
print("Shape of Array4 :",Array4.shape)
print("Shape of Array5_0 :",Array5_0.shape) 
print("Shape of Array5_1 :",Array5_1.shape)
print("Shape of Array5_2 :",Array5_2.shape)
print("Shape of Array6 :",Array6.shape)
print("Shape of Array7_0 :",Array7_0.shape) 
print("Shape of Array7_1 :",Array7_1.shape)
print("Shape of Array7_2 :",Array7_2.shape)
print("Shape of Array8 :",Array8.shape) 
print("Shape of Array9 :",Array9.shape)
print("Shape of Array10 :",Array10.shape) 
print("Shape of Array11 :",Array11.shape) 
print("----------------------------------------------")
print("Dimentions of Array1 :",Array1.ndim)
print("Dimentions of Array2 :",Array2.ndim)
print("Dimentions of Array3 :",Array3.ndim)
print("Dimentions of Array4 :",Array4.ndim)
print("Dimentions of Array5_0 :",Array5_0.ndim)
print("Dimentions of Array5_1 :",Array5_1.ndim)
print("Dimentions of Array5_2 :",Array5_2.ndim)
print("Dimentions of Array6 :",Array6.ndim)
print("Dimentions of Array7_0 :",Array7_0.ndim)
print("Dimentions of Array7_1 :",Array7_1.ndim)
print("Dimentions of Array7_2 :",Array7_2.ndim)
print("Dimentions of Array8 :",Array8.ndim)
print("Dimentions of Array9 :",Array9.ndim)
print("Dimentions of Array10 :",Array10.ndim)
print("Dimentions of Array11 :",Array11.ndim)

Shape of Array1 : (7,)
Shape of Array2 : (10,)
Shape of Array3 : (10,)
Shape of Array4 : (10,)
Shape of Array5_0 : (2, 2)
Shape of Array5_1 : (3, 3)
Shape of Array5_2 : (5, 5)
Shape of Array6 : (10,)
Shape of Array7_0 : (2, 2)
Shape of Array7_1 : (3, 3)
Shape of Array7_2 : (5, 5)
Shape of Array8 : (2, 5)
Shape of Array9 : (2, 2)
Shape of Array10 : (3, 3)
Shape of Array11 : (5, 3)
----------------------------------------------
Dimentions of Array1 : 1
Dimentions of Array2 : 1
Dimentions of Array3 : 1
Dimentions of Array4 : 1
Dimentions of Array5_0 : 2
Dimentions of Array5_1 : 2
Dimentions of Array5_2 : 2
Dimentions of Array6 : 1
Dimentions of Array7_0 : 2
Dimentions of Array7_1 : 2
Dimentions of Array7_2 : 2
Dimentions of Array8 : 2
Dimentions of Array9 : 2
Dimentions of Array10 : 2
Dimentions of Array11 : 2


# Example 1 : HOW THE COMPUTER READ AN IMAGE?

#### COMPUTERS CANNOT UNDERSTAND QUANTITATIVE INPUTS LIKE IMAGES,AUDIOS AND VIDEOS... SO THEY READ THE IMAGES,AUDIOS AND VIDEOS IN THE FORM OF NUMBERS....

##### LET'S SEE HOW A COMPUTER READ AN IMAGE.....
##### To read an image in python, we generally use a package called Image from PIL. But As we are going to Discuss about the opencv in future session. I would like to use opencv to read an image and then we can see how an image is represented in computers in the form of Matrices.

##### If you dont understand the following code Don't Worry. Later when we see OPENCV Package it would be clear. Until then Just look at the Output for now. 

#### What is opencv? We can discuss about that in the later weeks. But for now, Just understand OpenCV is just simply a package for python that enables to read images,videos from the webcam. We can discuss in a greater detail in later week...

In [8]:
import cv2
# cv2.imread("image path",mode of reading) Here we have passed path of image and mode as GRAYSCALE mode.
IMAGE = cv2.imread('C:\\users\\poorn\\data\\digit.png',cv2.IMREAD_GRAYSCALE) # This imread() method/function return an array corresponding to the input....
print("Type of the Image :",type(IMAGE))  # You can verify the type of the input image
print("Shape of image :",IMAGE.shape)
print("Dimentions of image :",IMAGE.ndim)

Type of the Image : <class 'numpy.ndarray'>
Shape of image : (10, 8)
Dimentions of image : 2


### Here it shows that the image is read in array format.... and the Image shape is of 10x18 and 2 dimentions as we read in grayscale format

In [9]:
IMAGE.reshape(10,8)

array([[  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  68, 245, 165,   0,   0],
       [  0,   0,   0, 168, 149, 165,   0,   0],
       [  0,   0, 102, 201, 102, 165,   0,   0],
       [  0,  21, 195,  59, 102, 165,   0,   0],
       [  0, 139, 165,   0, 102, 165,   0,   0],
       [  0, 205, 255, 255, 255, 255, 201,   0],
       [  0,   0,   0,   0, 102, 165,   0,   0],
       [  0,   0,   0,   0, 102, 165,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0]], dtype=uint8)

In [10]:
import matplotlib.pyplot as plt
plt.imshow(IMAGE)

### Observations :
##### From the above,
##### Firstly we have an image of number 4. Using OPENCV we have read the image. As we know that computer reads the image as collection of numbers arranged in a format.  The image is of 10 pixels  height and 8 pixels of width. Therefore the shape of the image is (10,8) Hence the output for the line  print("Shape of image :",IMAGE.shape) is (10,8). And as we read the image in GRAYSCALE format, The dimentions for that image is 2. If we have read the image in color format then the dimentions would be 3.


### Ignore the above code if you do not understand it for now. Just focus on the output for this session.


# Hope this Session helped you to understand how to create an Array in many Possible ways and how you understand about what is shape and dimentions.

## Thank you....
##### Notebook Prepared by: V.PoornaChand.
https://www.linkedin.com/in/poorna-chand-902642177/