In [1]:
import numpy as np

In [2]:
X = np.random.randint(0,30,(3,5)) # Creates a matrix of 3x5 randomly initialized with in the range 0 to 30...
print(X,"\nDimentions :",X.ndim,"\nShape :",X.shape)

[[27 23 28  9  6]
 [12 18 26  6 29]
 [ 1 12  3 20  9]] 
Dimentions : 2 
Shape : (3, 5)


# Content
        1. Min, Max with and without Axis as parameter
        2. Argmax, Argmin with and without Axis as parameter
        3. Flatten
        4. Mean, Standard deviation, Variance
        5. Cumulative sum : cumsum()
        6. Sorting

In [3]:
print("Minimum value in the Given Matrix X :",X.min())
print("Maximum value in the Given Matrix X :",X.max())
print("Index value where the Minimum value in the Given Matrix X is Present:",X.argmin())
print("Index value where the Maximum value in the Given Matrix X is Present:",X.argmax())
print('''------------------------------------------------------------------------------------------------------------------
np.argmin() or np.argmax() functions first flatten the given multidimetnional matrix/array and then look for the 
min/max value respectively and then return the index value...
------------------------------------------------------------------------------------------------------------------
We have looked at the min, max function and argmin and argmax functions as well....... Now can we get the min and 
max values of individual rows and columns of the given matrix X ? The answer is YES!!!
------------------------------------------------------------------------------------------------------------------
Answer : We can achieve that by passing axis as the parameter value for Both the functions....
------------------------------------------------------------------------------------------------------------------''')
print("Minimum Values of each column in the Matrix X :",X.min(axis=0))
print("Minimum Values of each Row in the Matrix X :",X.min(axis=1))
print("Maximum Values of each column in the Matrix X :",X.max(axis=0))
print("Maximum Values of each Row in the Matrix X :",X.max(axis=1))
print("Index Values Where Minimum Values of each column in the Matrix X :",X.argmin(axis=0))
print("Index Values Where Minimum Values of each row in the Matrix X :",X.argmin(axis=1))
print("Index Values Where Maximum Values of each column in the Matrix X :",X.argmax(axis=0))
print("Index Values Where Maximum Values of each row in the Matrix X :",X.argmax(axis=1))
print("Flattened Matrix :",X.ravel())

Minimum value in the Given Matrix X : 1
Maximum value in the Given Matrix X : 29
Index value where the Minimum value in the Given Matrix X is Present: 10
Index value where the Maximum value in the Given Matrix X is Present: 9
------------------------------------------------------------------------------------------------------------------
np.argmin() or np.argmax() functions first flatten the given multidimetnional matrix/array and then look for the 
min/max value respectively and then return the index value...
------------------------------------------------------------------------------------------------------------------
We have looked at the min, max function and argmin and argmax functions as well....... Now can we get the min and 
max values of individual rows and columns of the given matrix X ? The answer is YES!!!
------------------------------------------------------------------------------------------------------------------
Answer : We can achieve that by passing axis as the

In [4]:
print("Mean of the Matrix X :",X.mean())
print("SD of the Matrix X :",X.std())
print("Variance of Matrix X :",X.var())
print("------------------------------------------------------------------------------------------------------------------")
print("---> To get individual row/column mean,std,var we can pass axis as the parameter here too.........")
print("------------------------------------------------------------------------------------------------------------------")
print("Individual Mean's of each column of the Matrix X :",X.mean(axis = 0))
print("Individual SD's of each column of the Matrix X :",X.std(axis = 0))
print("Individual variances of each column of Matrix X :",X.var(axis = 0))
print("------------------------------------------------------------------------------------------------------------------")
print("Individual Mean's of each row of the Matrix X :",X.mean(axis = 1))
print("Individual SD's of each row of the Matrix X :",X.std(axis = 1))
print("Individual variances of each row of Matrix X :",X.var(axis = 1))
print("------------------------------------------------------------------------------------------------------------------")

Mean of the Matrix X : 15.266666666666667
SD of the Matrix X : 9.377040518675862
Variance of Matrix X : 87.92888888888888
------------------------------------------------------------------------------------------------------------------
---> To get individual row/column mean,std,var we can pass axis as the parameter here too.........
------------------------------------------------------------------------------------------------------------------
Individual Mean's of each column of the Matrix X : [13.33333333 17.66666667 19.         11.66666667 14.66666667]
Individual SD's of each column of the Matrix X : [10.65624491  4.49691252 11.34313302  6.01849003 10.20892855]
Individual variances of each column of Matrix X : [113.55555556  20.22222222 128.66666667  36.22222222 104.22222222]
------------------------------------------------------------------------------------------------------------------
Individual Mean's of each row of the Matrix X : [18.6 18.2  9. ]
Individual SD's of each row 

In [5]:
print("Cumulative sum of the given matrix X :",X.cumsum()) # np.cumsum(X) is also valid...

Cumulative sum of the given matrix X : [ 27  50  78  87  93 105 123 149 155 184 185 197 200 220 229]


In [6]:
print("Sorted Matrix/Array X : This will sort the each row elements... By passing axis as parameter we can decide sort order...")
X.sort(axis=1) # Row wise sorting
print(X)
print('----------------------')
X.sort(axis=0) # Column wise sorting
print(X)

Sorted Matrix/Array X : This will sort the each row elements... By passing axis as parameter we can decide sort order...
[[ 6  9 23 27 28]
 [ 6 12 18 26 29]
 [ 1  3  9 12 20]]
----------------------
[[ 1  3  9 12 20]
 [ 6  9 18 26 28]
 [ 6 12 23 27 29]]


### This was the end of Numpy Lectures for Machine Learning !!!
### The concepts that we have discussed till now are quite enough for starting with machine learning....Any Missed topics or further topics will be discussed here soon....
### Hope this session was helpful..... Thank you

##### Notebook Prepared By : V.PoornaChand. 
https://www.linkedin.com/in/poorna-chand-902642177/